# Generated by Django 3.2.7 on 2021-10-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keshavnursery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
